language: android

android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    - sys-img-armeabi-v7a-android-27

   #licenses:
    #- 'android-sdk-preview-license-.+'
    #- 'android-sdk-license-.+'
    #- 'google-gdk-license-.+'
    #
    #

before_install:
   - yes | sdkmanager "platforms;android-27"
   - yes | sdkmanager "build-tools;27.0.3"

# Emulator Management: Create, Start and Wait
#before_script:
   #- chmod +x gradlew

script:
  - "./gradlew assembleRelease"
